baseURL = "https://pir.nz/"
languageCode = 'en-uk'
title = "pir.nz"
theme = "hugo-ink"
#paginate = 5

enableGitInfo = true

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[taxonomies]
  order = 'orders'
  family = 'families'
  subfamily = 'subfamilies'
  genus = 'genera'
  tag = 'tags'
  
[params]
	favicon = "/icon/favicon.ico"
	subtitle = ""
	mainSections = ["posts"]
	# Optional 64x64 avatar image.
	avatar = "/icon/android-chrome-192x192.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Plants"
url = "/garden/"
weight = 3

[[menu.main]]
name = "Personal notes"
url = "https://notas.de.pir.nz/"
weight = 4


# [[params.social]]
# name = "Github"
# icon = "github"
# url = "https://github.com/knadh/hugo-ink"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[markup.goldmark.renderer]
unsafe= true
